[package]
name = "transmission"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = []

[dependencies]
heapless = "0.7.16"
postcard = "1.0.2"
serde = "1.0.147"
serde_derive = "1.0.147"
bbqueue = "0.5.1"
